apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-apache
spec:
  replicas: 5
  selector:
    matchLabels:
      app: apache
    matchExpressions:
      - {key: app, operator: In, values: [apache]}
  template:
    metadata:
      name: apache
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
